### ISSUE TITLE
Rhea - weird geometry left in RCS ports

### ISSUE THREAD

**Issue by blowfishpro** [ChrisAdderley/NearFutureSpacecraft#101]
I'm guessing it just needs to be deleted?  Two of the four RCS clusters seem to have this (though it's not in exactly the same place)

![screenshot0](https://user-images.githubusercontent.com/10545461/46253505-34520700-c432-11e8-87d5-d1229f050463.png)

**Comment by ChrisAdderley** [comment]
Ah yeah some kind of dummies hanging around, will address... soon
