### ISSUE TITLE
Mk4-1 'Amalthea' Missing RCS Transforms.

### ISSUE THREAD

**Issue by 51ngular1ty** [ChrisAdderley/NearFutureSpacecraft#102]
![screenshot6](https://user-images.githubusercontent.com/2055883/46576826-f73dc580-c999-11e8-9c28-379b1b0380ec.png)
![screenshot1](https://user-images.githubusercontent.com/2055883/46576832-500d5e00-c99a-11e8-9431-a1a7ca7584af.png)
I wanted to report this. Otherwise these parts are looking great.  Thank you for your hard work.

**Comment by ChrisAdderley** [comment]
At the moment the dev branch is not really stable enough to test. There's a bit to go before that, but I will indeed ensure this gets fixed.
