### ISSUE TITLE
Typo in NFSpacecraftUSILifeSupport.cfg

### ISSUE THREAD

**Issue by quasitonality** [ChrisAdderley/NearFutureSpacecraft#108]
I think there's a typo in the USI-LS config file:

```
	MODULE
	{
		name = ModuleHabitation
		BaseKerbalMonths = #$/mass$
		@BaseKerbalMonths *= 10
		@BaseKerbalMonths -= #$/CrewCapacity$
		CrewCapacity = #$/CrewCapacity$
		BaseHabMultiplier = 0

		ConverterName = #LOC_NFSpacecraft_Action_ConverterHabName
		StartActionName = #LOC_NFSpacecraft_Action_StartUSIHab
		StopActionName = #LOC_NFSpacecraft_Action_StopUSIHab
		ToggleActionName = #LOC_NFSpacecraft_Action_ToggleUSIHab


		INPUT_RESOURCE
		{
			ResourceName = ElectricCharge
			Ratio = #$../BaseKerbalMonths$
			@Ratio *= .25
		}
	}
```

Since everything else in the Itinerant is directly scaled from the Hitchhiker, I think line 92 was intended to be `@Ratio *= 0.025`. (Roverdude's config file has `Ratio = 0.525` for the Hitchhiker, which is equal to `BaseKerbalMonths * 0.025`)

**Comment by ChrisAdderley** [comment]
How sure would you rank this? I don't have any insight into this external compat kinda stuff. If this is 100% true then I'm happy to make the change though.

**Comment by ChrisAdderley** [comment]
Released fix.
