### ISSUE TITLE
Basic FAR support for Command Pods

### ISSUE THREAD

**Issue by HSJasperism** [ChrisAdderley/NearFutureSpacecraft#113]
@ChrisAdderley 

Good day.

Right now, FAR removes ModuleLiftingSurface from command modules since FAR's simulation should handle the lifting characteristics. This avoids having parts with ridiculous amounts of lift. FAR doesn't do blanket removal of all instances of the module since not all mods use ModuleLiftingSurface as originally intended by Squad.

Is it alright with you if I submitted a pull request to the dev branch regarding this? Also, would you prefer the patches be in a separate file or should the patches be in the part cfgs?

**Comment by ChrisAdderley** [comment]
Sorry, I missed this - too many mods. Saw this in this update cycle - I have added the requisite stuff

**Comment by ChrisAdderley** [comment]
Released fix.
