### ISSUE TITLE
Mk4-B 'Elara' Biconic Command Module IVA glitch

### ISSUE THREAD

**Issue by TJCizadlo** [ChrisAdderley/NearFutureSpacecraft#115]
A visit Duna poster is visible outside of the capsule when cutaway view is enabled.
[http://www.cizadlo.us/Images/KSP/161/screenshot0.png](http://www.cizadlo.us/Images/KSP/161/screenshot0.png)

**Comment by ChrisAdderley** [comment]
Solved for 1.1.0

**Comment by ChrisAdderley** [comment]
Released fix.
