### ISSUE TITLE
3.75m Orbital Command Pod Top Attachment Node is Off

### ISSUE THREAD

**Issue by Forgilageord** [ChrisAdderley/NearFutureSpacecraft#116]
I can't remember the name of the part off the top of my head, but I'm referring to the flat 3.75m pod with four long windows, the one in the screenshot on the forum page. The top node is slightly too low, resulting in many things placed on top of this pod to z-fight with the pod itself, requiring the tiniest adjustment with the translation tool to look right.

**Comment by ChrisAdderley** [comment]
Found and solved for 1.1.0

**Comment by ChrisAdderley** [comment]
Released fix.
