### ISSUE TITLE
MK4-1 variant - menu pop-up issue

### ISSUE THREAD

**Issue by bob82fr** [ChrisAdderley/NearFutureSpacecraft#127]
Hi,

When changing MK4-1 variant, the menu pop-up keep old settings. You need to select it again to have the correct pop-up menu (when choosing a new variant, old resources needed stay in the pop-up with new ones).
I ve got the same bug with Cry Tanks parts.
KSP 1.7.1 by steam.
Mods installed : Near future mod with + all dependences mods (without Atomic) + EVE

Bye

**Comment by ChrisAdderley** [comment]
It's a bug in 1.7.1 that required mitigation in B9PartSwitch. Download B9PS 2.8.0 to resolve it.
