### ISSUE TITLE
Drag cube of PPD-1

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFutureSpacecraft#13]
Just adding a note here so it doesn't get lost.

**Comment by ChrisAdderley** [comment]
Is this still a problem? I shipped two potential fixes for this in the last version.

**Comment by lOmicronl** [comment]
Snark specifically mentioned it here: http://forum.kerbalspaceprogram.com/index.php?/topic/140763-is-there-a-command-pod-that-has-higher-seating-capacity/#comment-2609314

**Comment by helaeon** [comment]
I'm still seeing the large drag cube with the latest dev version. In partdatabase.cfg
```
PART
{
	url = NearFutureSpacecraft/Parts/Command/command-pods/command-ppd-1/command-ppd-1
	DRAG_CUBE
	{
		cube = Default, 5.219,0.6926,2.773, 5.219,0.6927,2.773, 10.85,0.7577,1.486, 10.86,0.9599,0.9164, 5.155,0.6817,2.773, 5.155,0.6898,2.773, 0,0.0284,0, 5.367,1.57,5.367
	}
}
```

**Comment by ChrisAdderley** [comment]
Ok, let's investigate this a little further

1. The drag cube of the Mk1-2
![screenshot284](https://user-images.githubusercontent.com/5642064/26939660-d67e2704-4c2c-11e7-93b3-8e4a7f26124a.png)
This will be the gold standard.
```
X: 3.3
Y: 4.6
Z: 3.3
```

2. The drag cube of the Mk3-9
![screenshot287](https://user-images.githubusercontent.com/5642064/26939728-152979d6-4c2d-11e7-90d1-40f155b3554b.png)
Also good, we expect it to be very similar to the Mk1-2, but it is a bit taller. This is more or less just confirming that my exports are right
```
X: 3.6
Y: 4.9
Z: 3.6
```

3. The drag cube of the PPD-1
![screenshot286](https://user-images.githubusercontent.com/5642064/26939795-4c73a9f2-4c2d-11e7-855f-be8926d81103.png)
This actually doesn't look anomalous. The X and Z components are about what we'd expect considering that the cross sectional area in these directions is about 1.5x the mk1-2. And the Y-component looks ok as well, mathematically the Y cross-sectional area is about doubled by increasing from 2.5 to 3.75m diameter.
```
X: 5.2
Y: 10.8
Z: 5.2
```

4. The drag cube of the Mk4-1
![screenshot285](https://user-images.githubusercontent.com/5642064/26939929-bdf9f31a-4c2d-11e7-87d5-25c23bbee06b.png)
If anything, this is the anomalous-looking cube. The X/Y components look ok, considerably more height on this pod, but the Y area is quite a bit more despite it being more aerodynamic and the same diameter as the PPD-1. huh.
```
X: 11
Y: 19
Z: 11
```

My conclusion here is that the PPD-1 is fine but the Mk4-1 might not be. 
What are your thoughts?

**Comment by helaeon** [comment]
Thanks for looking into it. I think my error was not realizing those were areas, not linear dimensions.
The Mk3 cockpit is also roughly the same diameter as the PPD-1 and Mk4-1:

> X: 12.45
> Y: 10.30
> Z: 11.78
I pulled open the MAV pod from the aborted Martian mod which is very similar in dimension to the PPD-1 and get:
![screenshot0](https://user-images.githubusercontent.com/9005153/26957586-34fbb912-4c83-11e7-94a3-ffd4b8a45942.png)

> X: 7.07
> Y: 11.35
> Z: 7.01
I put the PPD-1 in a fairly form fitting fairing to see what happened:
![screenshot1](https://user-images.githubusercontent.com/9005153/26957861-dee8df9e-4c84-11e7-99ba-1dad013060fe.png)
So I think you are correct that the PPD-1 is good. About 10 for Y is the correct value.

I put a MK4-1 in a fairly form fitting fairing and found:
![screenshot3](https://user-images.githubusercontent.com/9005153/26958104-0eeacc7e-4c86-11e7-9c05-7c33bea83408.png)

> X: 11.95
> Y: 14.25
> Z: 11.97

I'm thinking a Y around 10-12 is probably correct for the Mk4-1 and the x and z are probably correct.

**Comment by ChrisAdderley** [comment]
Resolved, was due a a problem with B9PartSwitch.
