### ISSUE TITLE
Mk3-9 Crew Portraits Obstructed

### ISSUE THREAD

**Issue by RyanRising** [ChrisAdderley/NearFutureSpacecraft#139]
The crew portraits for the Mk3-9 "Rhea" Orbital Command Pod are partially blocked by what I assume to be part of the IVA control panel. Only occurs with male Kerbals. See https://forum.kerbalspaceprogram.com/index.php?/topic/155465-19x-near-future-technologies-nflv-20-may-2nd/&do=findComment&comment=3790498 for logs and a picture.

**Comment by ChrisAdderley** [comment]
I can't repro this in 1.10.1, can you confirm?
![screenshot259](https://user-images.githubusercontent.com/5642064/89150255-013b9b80-d513-11ea-968b-f2e4c9da1dc3.png)

**Comment by RyanRising** [comment]
Looks like you're using female Kerbals. I've only had it appear with the male ones.
![screenshot0](https://user-images.githubusercontent.com/65933674/89150960-a4d97b80-d514-11ea-8f41-2fce94ce300a.png

**Comment by ChrisAdderley** [comment]
Ah... missed that, will look into it next version (again)

**Comment by ChrisAdderley** [comment]
Should be fixed now

**Comment by RyanRising** [comment]
Confirmed as fixed, thank you.
