### ISSUE TITLE
Mk3-9 comand pod IVA glitch

### ISSUE THREAD

**Issue by WildLynxDev** [ChrisAdderley/NearFutureSpacecraft#14]
Some sort of handle are misaligned, and located in the middle of the MFD instead of it's shaft.
http://i.imgur.com/GJtTznA.png
http://i.imgur.com/xe7Nntw.png

P.S. May be it's better to use standard RPM assets like in any RPM enabled stock cabins? Less work and pilots can learn how to use NFT(SC) cabins faster?

**Comment by ChrisAdderley** [comment]
Closing this issue, prop issues go in NFProps repo
