### ISSUE TITLE
Pilot seat orientation in PPD-1

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/NearFutureSpacecraft#31]
Please rotate pilot seats by 45 degrees to align them with part orientation. Piloting it in IVA is hard when view is tilted.
Yes, that would result in a weird looking cockpit with tilted porthole, but in this case weird=cool. See sketch:
![ppd-1](https://cloud.githubusercontent.com/assets/4061903/20249852/c7f30726-aa1b-11e6-959f-1a91b1ea9f8a.png)

**Comment by ChrisAdderley** [comment]
Would require complete remodel/unwrap of cockpit, really not going to happen.
