### ISSUE TITLE
fix for Extras\OrbitalLFOEngines\OrbitalEnginesLFO.cfg

### ISSUE THREAD

**Issue by OliverPA77** [ChrisAdderley/NearFutureSpacecraft#40]
I'm trying to provide a fix for this file but can't find it here on Git.
The issue is that this file patches the engines to use LFO rather than Mono propellant, but does not change the integrated tank types.

You'd need to add this to orbital-engine-25 and orbital-engine-375:
```
	@MODULE[ModuleB9PartSwitch]
	{
		@SUBTYPE[Integrated]
		{
			@tankType = LFO
		}
	}
```

[OrbitalEnginesLFO.cfg.txt](https://github.com/ChrisAdderley/NearFutureSpacecraft/files/756978/OrbitalEnginesLFO.cfg.txt)

**Comment by ChrisAdderley** [comment]
Check the dev branch, but fixed in 29ebb78
