### ISSUE TITLE
Suggestion: Allow the RCS blocks to use LH2/O if CryoEngines is installed

### ISSUE THREAD

**Issue by Xaryen** [ChrisAdderley/NearFutureSpacecraft#49]
Sorry for bothering with this, but I thought it would be a neat idea to be able to have a form of RCS that can utilize LH2/O to simulate something similar to the Integrated Vehicle Fluid System on ACES.

My very limited knowledge of KSP moding and MM tells me it could be possible to implement this as a switch in the VAB in order to not expand the part list.

It would probably be less powerful than Monoprop trusters for balance but stronger that the magnetoplasmatic ones (so ~0.6 thruster power) and have slightly lower Isp than the LH2/O engines because they are pressure fed (so around 400-430 I guess).

**Comment by ChrisAdderley** [comment]
The RCS module doesn't support the MultiModeEngine module, so there would need to be either custom code work or more parts to accomplish this. 

It's an interesting idea though.

**Comment by ChrisAdderley** [comment]
The functionality of specific biprop RCS exists for parts in NFLV now and I've decided it will stay there, so closing this for now.
