### ISSUE TITLE
Mk4-1 pod does not show up as any vessel icon in map mode.

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFutureSpacecraft#54]
Shows as "ship" in tracking station, but lacks an icon entirely in map view.

(Independent of what type filter is set.)

**Comment by ChrisAdderley** [comment]
Might be a bug in B9PartSwitch, under investigation.

**Comment by ChrisAdderley** [comment]
Traced to [stock issue exacerbated by B9PartSwitch](http://forum.kerbalspaceprogram.com/index.php?/topic/140541-13-b9partswitch-v180-may-27-switch-fuels-models-nodes-and-more/&do=findComment&comment=3096307)

Keeping an eye on this for now.

**Comment by ChrisAdderley** [comment]
Now resolved.
