### ISSUE TITLE
3-way RCS blocks

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/NearFutureSpacecraft#6]
As I pointed out [here](http://forum.kerbalspaceprogram.com/index.php?/topic/129521-wip-rcs-size-variants-and-new-options/), the most 'cleanly' useful RCS blocks are 3-way corner blocks. No ship-facing nozzles.

NFS could definitely use such thing.

**Comment by ChrisAdderley** [comment]
Added in upcoming 0.5.4
