### ISSUE TITLE
Suggestion: Add integrated RCS to Mk3-9 Command Pod

### ISSUE THREAD

**Issue by Stratickus** [ChrisAdderley/NearFutureSpacecraft#64]
The 3-9 appears to have multiple ports/vents that look like they are meant for an integrated RCS system. Possibly the Mk4-1 as well. Disregard if this is not an intended feature.

Idea taken from VSR Mk1-2 Command Pod.

Cheers,

**Comment by ChrisAdderley** [comment]
Nah, probably not going to do this. I added them for decoration, I bet they're horribly unbalanced and not that useful.
