### ISSUE TITLE
LT-POD Legs prone to overheat and destruction. Add heat resistant model with higher resistance/ablator?

### ISSUE THREAD

**Issue by skrelk** [ChrisAdderley/NearFutureSpacecraft#70]
The LT-POD Landing Assembly Legs are pretty to overheating and burning up on reentry. Could we get a new version that has a higher heat resistance and/or ablator to make the legs more useful for reusable capsules?

**Comment by ChrisAdderley** [comment]
I thought there was a bug here maybe, but they are set to a heat tolerance of 2400K! That's pretty crazy already... more than the Mk3 cockpit, for example!

**Comment by ChrisAdderley** [comment]
I'll keep this open for now, I bumped the emssivity and the skin max temp for the next update though.

**Comment by skrelk** [comment]
Thanks, it helps a lot, gets it to the point where the legs work good for a reentry as long as there is a heatshield on the main body of the craft
