### ISSUE TITLE
Lack of docking view in IVA

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/NearFutureSpacecraft#8]
There is no button to enable docking view on MFDs.

Probably more missing stuff compared to default RPM MFDs.

**Comment by ChrisAdderley** [comment]
Some of the buttons have more than one mode when you click them. I'm not at home now but I though that docking was indeed supported as a second mode on one button.

**Comment by Vladimir-csp** [comment]
I've found it and also why I didn't find sooner. On the main screens of Mk3-9 pod the docking view is broken and outputs only incomplete file path of something in `NearFutureProps/.../large_pg_target...` (And camera view if reference port is selected, so only data overlay is broken)
Docking on side screens works, but overlay is misaligned.
Also some backgrounds are white, not sure if this is intentional

![main](https://cloud.githubusercontent.com/assets/4061903/12396700/e74cde06-be19-11e5-8559-e5b69192c9db.png)
![side](https://cloud.githubusercontent.com/assets/4061903/12396698/e74a4b6e-be19-11e5-9f62-93eb38cfbc55.png)
![white](https://cloud.githubusercontent.com/assets/4061903/12396699/e74c7696-be19-11e5-90f2-6518a462b9de.png)

**Comment by ChrisAdderley** [comment]
Considering my current lack of time, marking this as wontfix for now

**Comment by ChrisAdderley** [comment]
I moved this issue to the NFProps repo
