### ISSUE TITLE
No Resource definition found for RESOURCE for PPD-24 Itinerant Service Container

### ISSUE THREAD

**Issue by MaximeBrean** [ChrisAdderley/NearFutureSpacecraft#86]
Error raised in KSP.log for the `PPD-24 Itinerant Service Container` part:
```
[LOG 13:06:20.074] PartLoader: Compiling Part 'NearFutureSpacecraft/Parts/Utility/utility-pod-25/utility-pod-25/utility-pod-25'
[ERR 13:06:20.090] [ShipTemplate]: No Resource definition found for RESOURCE

[WRN 13:06:20.102] Could not create PartResource of type 'ReplacementParts
```

The error is caused by the `NearFutureSpacecraft\Patches\NFSpacecraftUSILifeSupport.cfg` path which forcibly add ReplacementParts resources (l.96-104)

ReplacementParts are only needed if Extraplanetary-Launchpads mod is also present. Imho, the patch should then check for both mods.

**Comment by ChrisAdderley** [comment]
Released fix.
