### ISSUE TITLE
Node symmetry bug on "command-125-landing-1"

### ISSUE THREAD

**Issue by Tiankay64** [ChrisAdderley/NearFutureSpacecraft#89]
Probably a minor issue. Why trying to place the "not Superdraco" engines (Or anything else) into its 3x node around the "not a Dragon" pod with symmetry enabled, symmetry mode jumps to 4x and the engines cannot be attached. 2 nodes show correct shadow parts, while 1 has the part doubled and at a weird angle.

Set to 3x symmetry:
https://i.imgur.com/hV2m2PG.jpg

What happens:
https://i.imgur.com/ZB5w6P5.jpg

PS: Screenshots show modded install, but I verified it happens in a stock install with nothing but B9PS, NF Props and NF Spacecraft-dev

**Comment by ChrisAdderley** [comment]
Not really going to address this as a bug as this is in heavy dev and there are way more issues than this.
