### ISSUE TITLE
Itinerant model is upside-down

### ISSUE THREAD

**Issue by Wyzard256** [ChrisAdderley/NearFutureSpacecraft#90]
The exterior model of the PPD-24 Itinerant Service Container appears to be rotated 180° around the yaw axis (Unity's Z-axis).  In its default orientation in the VAB, the mission flag is upside-down, and the radiator panels are on the opposite side from where the RTGs appear in the IVA cutaway view.

Purely cosmetic; the part still works correctly.  (In particular, EVA kerbals still exit the hatch right-side-up.)

**Comment by ChrisAdderley** [comment]
Will adjust it when I'm reworking it.

**Comment by ChrisAdderley** [comment]
Fixed in 1.0.0 release
